SELECT T.AUTHOR_ID, A.AUTHOR_NAME, T.CATEGORY, T.TOTAL_SALES
FROM (SELECT B.AUTHOR_ID, B.CATEGORY, SUM(B.PRICE*S.SALES) TOTAL_SALES
    FROM BOOK B JOIN (SELECT BOOK_ID, SALES
        FROM BOOK_SALES
        WHERE TO_CHAR(SALES_DATE, 'YYYY-MM') = '2022-01') S
    ON B.BOOK_ID = S.BOOK_ID
    GROUP BY B.AUTHOR_ID, B.CATEGORY) T
    JOIN AUTHOR A
ON T.AUTHOR_ID = A.AUTHOR_ID
ORDER BY 1, 3 DESC;