WITH MILKS AS (
    SELECT CART_ID
    FROM CART_PRODUCTS 
    WHERE NAME = 'Milk'
), YOGURTS AS (
    SELECT CART_ID
    FROM CART_PRODUCTS 
    WHERE NAME = 'Yogurt'
)

SELECT DISTINCT M.CART_ID
FROM MILKS M JOIN YOGURTS Y
ON M.CART_ID = Y.CART_ID
ORDER BY 1;