SELECT A.PRODUCT_CODE, A.PRICE*B.SA AS SALES
FROM PRODUCT A JOIN (SELECT PRODUCT_ID, SUM(SALES_AMOUNT) SA
                     FROM OFFLINE_SALE
                     GROUP BY 1) B
ON A.PRODUCT_ID = B.PRODUCT_ID
ORDER BY 2 DESC, 1;