WITH RESERVATION AS (
    SELECT CAR_ID
    FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY 
    WHERE START_DATE <= DATE '2022-11-30' AND END_DATE >= DATE '2022-11-01'
)

SELECT C.CAR_ID, C.CAR_TYPE, C.DAILY_FEE * (100 - P.DISCOUNT_RATE) / 100 * 30 FEE
FROM CAR_RENTAL_COMPANY_CAR C JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN P
     ON C.CAR_TYPE = P.CAR_TYPE
WHERE C.CAR_ID NOT IN (SELECT * FROM RESERVATION)
AND C.CAR_TYPE IN ('세단', 'SUV')
AND P.DURATION_TYPE = '30일 이상'
AND C.DAILY_FEE * (100 - P.DISCOUNT_RATE) / 100 * 30 BETWEEN 500000 AND 2000000
ORDER BY 3 DESC, 2, 1 DESC;