SELECT I.FOOD_TYPE, I.REST_ID, I.REST_NAME, I.FAVORITES
FROM REST_INFO I JOIN (
    SELECT FOOD_TYPE, MAX(FAVORITES) MAX_FAVORITES
    FROM REST_INFO 
    GROUP BY FOOD_TYPE
) T
ON I.FOOD_TYPE = T.FOOD_TYPE
AND I.FAVORITES = T.MAX_FAVORITES
ORDER BY 1 DESC;
