SELECT ID,
CASE
    WHEN SIZE = 1 THEN 'CRITICAL'
    WHEN SIZE = 2 THEN 'HIGH'
    WHEN SIZE = 3 THEN 'MEDIUM'
    ELSE 'LOW'
END COLONY_NAME
FROM (SELECT ID, SIZE_OF_COLONY, NTILE(4) OVER (ORDER BY SIZE_OF_COLONY DESC) AS SIZE
      FROM ECOLI_DATA) D
ORDER BY 1