SELECT 
    U.USER_ID, 
    U.NICKNAME, 
    U.CITY || ' ' || U.STREET_ADDRESS1 || ' ' || U.STREET_ADDRESS2 AS 전체주소,
    SUBSTR(U.TLNO, 1, 3) || '-' || SUBSTR(U.TLNO, 4, 4) || '-' || SUBSTR(U.TLNO, 8, 4) AS 전화번호
FROM USED_GOODS_USER U JOIN (
    SELECT WRITER_ID
    FROM USED_GOODS_BOARD
    GROUP BY WRITER_ID
    HAVING COUNT(WRITER_ID) >= 3
) W
ON U.USER_ID = W.WRITER_ID
ORDER BY 1 DESC;
