SELECT I.REST_ID, I.REST_NAME, I.FOOD_TYPE, I.FAVORITES, I.ADDRESS, SCORE
FROM REST_INFO I JOIN (SELECT REST_ID, ROUND(AVG(REVIEW_SCORE),2) SCORE
                       FROM REST_REVIEW
                       GROUP BY REST_ID) S
ON I.REST_ID = S.REST_ID
WHERE I.ADDRESS LIKE '서울%'
ORDER BY 6 DESC, 4 DESC; 