SELECT TO_CHAR(S.SALES_DATE, 'YYYY') YEAR, 
       TO_NUMBER(TO_CHAR(S.SALES_DATE, 'MM')) MONTH, 
       U.GENDER GENDER, 
       COUNT(DISTINCT(U.USER_ID)) USERS
FROM USER_INFO U JOIN ONLINE_SALE S
ON U.USER_ID = S.USER_ID
WHERE U.GENDER IS NOT NULL
GROUP BY TO_CHAR(S.SALES_DATE, 'YYYY'), TO_CHAR(S.SALES_DATE, 'MM'), U.GENDER
ORDER BY 1, 2, 3;