SELECT EXTRACT (YEAR FROM SALES_DATE) YEAR,
       EXTRACT (MONTH FROM SALES_DATE) MONTH,
       U.GENDER,
       COUNT(DISTINCT O.USER_ID) USERS
FROM USER_INFO U JOIN ONLINE_SALE O
     ON U.USER_ID = O.USER_ID
WHERE U.GENDER IS NOT NULL
GROUP BY EXTRACT (YEAR FROM SALES_DATE), EXTRACT (MONTH FROM SALES_DATE), U.GENDER
ORDER BY 1, 2, 3;