SELECT CAR_ID,  
       TO_CHAR(ROUND(AVG(END_DATE+1 - START_DATE),1), 'FM9999.0') AS "AVERAGE_DURATION"
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
GROUP BY CAR_ID
HAVING AVG(END_DATE+1 - START_DATE) >= 7
ORDER BY TO_NUMBER(AVERAGE_DURATION) DESC, CAR_ID DESC ;