# SELECT O.ANIMAL_ID, O.NAME
# FROM ANIMAL_INS I RIGHT JOIN ANIMAL_OUTS O
# ON I.ANIMAL_ID = O.ANIMAL_ID
# WHERE O.NAME IS NOT NULL

SELECT O.ANIMAL_ID, O.NAME
FROM ANIMAL_INS I RIGHT JOIN ANIMAL_OUTS O
ON I.ANIMAL_ID = O.ANIMAL_ID
WHERE I.NAME IS NULL AND O.NAME IS NOT NULL