-- 코드를 입력하세요
# SELECT I.ANIMAL_ID, O.NAME
# FROM ANIMAL_INS I FULL OUTER JOIN ANIMAL_OUTS O
# ON I.ANIMAL_ID = O.ANIMAL_ID
# # WHERE (I.DATETIME IS NOT NULL AND O.DATETIME IS NULL)
# #     OR (I.DATETIME IS NULL AND O.DATETIME IS NOT NULL)
# ORDER BY 1

SELECT O.ANIMAL_ID, O.NAME
FROM ANIMAL_INS I RIGHT JOIN ANIMAL_OUTS O
ON I.ANIMAL_ID = O.ANIMAL_ID
WHERE I.DATETIME IS NULL AND O.DATETIME IS NOT NULL
ORDER BY 1


