WITH JOINMEMBERS AS(
    SELECT USER_ID
    FROM USER_INFO 
    WHERE TO_CHAR(JOINED, 'YYYY') = '2021'
), ALLMEMBER AS(
    SELECT COUNT(*) CNT
    FROM JOINMEMBERS
)

SELECT TO_CHAR(S.SALES_DATE, 'YYYY') YEAR, 
       TO_NUMBER(TO_CHAR(S.SALES_DATE, 'MM')) MONTH, 
       COUNT(DISTINCT S.USER_ID) PURCHASED_USERS, 
       ROUND(COUNT(DISTINCT S.USER_ID) /CNT, 1) PUCHASED_RATIO
FROM ONLINE_SALE S JOIN JOINMEMBERS J
ON S.USER_ID = J.USER_ID, ALLMEMBER
GROUP BY TO_CHAR(S.SALES_DATE, 'YYYY'), TO_CHAR(S.SALES_DATE, 'MM'), CNT
ORDER BY 1, 2;