WITH TMP AS (
    SELECT HISTORY_ID, END_DATE - START_DATE + 1 AS DAYS, CAR_TYPE, C.DAILY_FEE
    FROM CAR_RENTAL_COMPANY_CAR C JOIN CAR_RENTAL_COMPANY_RENTAL_HISTORY H
         ON C.CAR_ID = H.CAR_ID
    WHERE C.CAR_TYPE = '트럭'
)

SELECT HISTORY_ID,
       T.DAILY_FEE * (100 - NVL(P.DISCOUNT_RATE, 0)) / 100 * T.DAYS FEE
FROM TMP T LEFT JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN P
     ON T.CAR_TYPE = P.CAR_TYPE
     AND P.DURATION_TYPE = 
        CASE
            WHEN T.DAYS >= 90 THEN '90일 이상'
            WHEN T.DAYS >= 30 THEN '30일 이상'
            WHEN T.DAYS >= 7 THEN '7일 이상'
            ELSE NULL
        END
ORDER BY 2 DESC, 1 DESC;