SELECT 
    T.HISTORY_ID, 
    T.DAILY_FEE * (100 - NVL(DISCOUNT_RATE, 0))/100 * T.DIFFDATE FEE
FROM CAR_RENTAL_COMPANY_DISCOUNT_PLAN P RIGHT JOIN (
    SELECT 
        H.HISTORY_ID, 
        C.CAR_ID, 
        C.CAR_TYPE, 
        C.DAILY_FEE, 
        TRUNC(H.END_DATE) - TRUNC(H.START_DATE) + 1 AS DIFFDATE
    FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY H
        JOIN CAR_RENTAL_COMPANY_CAR C
        ON H.CAR_ID = C.CAR_ID
) T
ON P.CAR_TYPE = T.CAR_TYPE
AND P.DURATION_TYPE =
    CASE
        WHEN T.DIFFDATE >= 90 THEN '90일 이상'
        WHEN T.DIFFDATE >= 30 THEN '30일 이상'
        WHEN T.DIFFDATE >= 7 THEN '7일 이상'
        ELSE NULL
    END
WHERE T.CAR_TYPE = '트럭'
ORDER BY 2 DESC, 1 DESC;