SELECT J.FLAVOR
FROM (SELECT FLAVOR, SUM(TOTAL_ORDER) TOTAL_ORDER
    FROM JULY
    GROUP BY FLAVOR) J
    JOIN FIRST_HALF H
ON J.FLAVOR = H.FLAVOR
ORDER BY J.TOTAL_ORDER + H.TOTAL_ORDER DESC
FETCH FIRST 3 ROWS ONLY;