WITH TMP AS (
    SELECT FLAVOR, SUM(TOTAL_ORDER) TOTAL_ORDER
    FROM JULY
    GROUP BY FLAVOR
)

SELECT H.FLAVOR
FROM FIRST_HALF H JOIN TMP T
     ON H.FLAVOR = T.FLAVOR
ORDER BY H.TOTAL_ORDER + T.TOTAL_ORDER DESC
FETCH FIRST 3 ROWS ONLY;