WITH TMP AS (SELECT *
    FROM APPOINTMENT 
    WHERE TO_CHAR(APNT_YMD, 'YYYY-MM-DD') = '2022-04-13'
    AND APNT_CNCL_YN = 'N'
    AND MCDP_CD = 'CS'
)

SELECT T.APNT_NO, P.PT_NAME, P.PT_NO, T.MCDP_CD, D.DR_NAME, T.APNT_YMD
FROM PATIENT P JOIN TMP T
     ON P.PT_NO = T.PT_NO
     JOIN DOCTOR D
     ON D.DR_ID = T.MDDR_ID
ORDER BY 6;
    