SELECT H.HOUR, COUNT(O.DATETIME) COUNT
FROM ANIMAL_OUTS O RIGHT JOIN (
    SELECT LEVEL - 1 AS hour
    FROM dual
    CONNECT BY LEVEL <= 24
    ORDER BY hour) H
ON TO_NUMBER(TO_CHAR(O.DATETIME, 'HH24')) = H.HOUR
GROUP BY H.HOUR
ORDER BY 1;