WITH HOURS AS (
    SELECT LEVEL - 1 HOUR
    FROM DUAL
    CONNECT BY LEVEL <= 24
), GROUP_OUTS AS (
    SELECT TO_NUMBER(TO_CHAR(DATETIME, 'HH24')) HOUR, COUNT(*) COUNT
    FROM ANIMAL_OUTS 
    GROUP BY TO_NUMBER(TO_CHAR(DATETIME, 'HH24'))
)

SELECT H.HOUR, NVL(O.COUNT, 0) COUNT
FROM HOURS H LEFT JOIN GROUP_OUTS O
     ON H.HOUR = O.HOUR
ORDER BY 1;