WITH HOURS AS(
    SELECT LEVEL - 1 HOUR
    FROM DUAL
    CONNECT BY LEVEL <= 24
)

SELECT H.HOUR, COUNT(O.DATETIME) COUNT
FROM ANIMAL_OUTS O RIGHT JOIN HOURS H
ON TO_NUMBER(TO_CHAR(O.DATETIME, 'HH24')) = H.HOUR
GROUP BY H.HOUR
ORDER BY 1;