SELECT TO_NUMBER(TO_CHAR(DATETIME, 'HH24')) HOUR, COUNT(*) COUNT
FROM ANIMAL_OUTS
WHERE TO_NUMBER(TO_CHAR(DATETIME, 'HH24')) >= 9
AND TO_NUMBER(TO_CHAR(DATETIME, 'HH24')) <= 19
GROUP BY TO_CHAR(DATETIME, 'HH24')
ORDER BY 1;