WITH REVIEWERS AS(
    SELECT MEMBER_ID
    FROM REST_REVIEW
    GROUP BY MEMBER_ID
    HAVING COUNT(*) = (
        SELECT MAX(COUNT(*))
        FROM REST_REVIEW 
        GROUP BY MEMBER_ID
    )
)

SELECT P.MEMBER_NAME, RV.REVIEW_TEXT, TO_CHAR(REVIEW_DATE, 'YYYY-MM-DD') REVIEW_DATE
FROM REVIEWERS R JOIN REST_REVIEW RV
ON R.MEMBER_ID = RV.MEMBER_ID
JOIN MEMBER_PROFILE P
ON R.MEMBER_ID = P.MEMBER_ID
ORDER BY 3, 2;