SELECT M.MEMBER_NAME, R.REVIEW_TEXT, TO_CHAR(REVIEW_DATE, 'YYYY-MM-DD') REVIEW_DATE
FROM MEMBER_PROFILE M JOIN REST_REVIEW R
     ON M.MEMBER_ID = R.MEMBER_ID
WHERE M.MEMBER_ID IN (
    SELECT MEMBER_ID
    FROM REST_REVIEW  
    GROUP BY MEMBER_ID
    HAVING COUNT(*) = (
        SELECT MAX(COUNT(*)) MAX_REVIEW_CNT
        FROM REST_REVIEW
        GROUP BY MEMBER_ID
    )
)
ORDER BY 3, 2;