SELECT 
    TO_NUMBER(TO_CHAR(START_DATE, 'MM')) AS MONTH,
    CAR_ID,
    COUNT(*) AS RECORDS
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
WHERE START_DATE BETWEEN DATE '2022-08-01' AND DATE '2022-10-31'
  AND CAR_ID IN (
        SELECT CAR_ID
        FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
        WHERE START_DATE BETWEEN DATE '2022-08-01' AND DATE '2022-10-31'
        GROUP BY CAR_ID
        HAVING COUNT(*) >= 5
  )
GROUP BY TO_CHAR(START_DATE, 'MM'), CAR_ID
ORDER BY TO_CHAR(START_DATE, 'MM'), CAR_ID DESC;
