SELECT YEAR, MAX - SIZE_OF_COLONY AS YEAR_DEV, ID
FROM ECOLI_DATA E JOIN(
    SELECT MAX(SIZE_OF_COLONY) MAX, YEAR(DIFFERENTIATION_DATE) YEAR
    FROM ECOLI_DATA
    GROUP BY YEAR(DIFFERENTIATION_DATE)
) G
ON YEAR(E.DIFFERENTIATION_DATE) = G.YEAR
ORDER BY 1, 2