SELECT DISTINCT C.CAR_ID
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY H
     JOIN CAR_RENTAL_COMPANY_CAR C
     ON H.CAR_ID = C.CAR_ID
WHERE CAR_TYPE = '세단'
      AND EXTRACT(MONTH FROM START_DATE) = 10
ORDER BY 1 DESC;