SELECT DISTINCT(C.CAR_ID)
FROM CAR_RENTAL_COMPANY_CAR C JOIN CAR_RENTAL_COMPANY_RENTAL_HISTORY H
ON C.CAR_ID = H.CAR_ID
WHERE TO_CHAR(H.START_DATE, 'MM') = '10'
AND C.CAR_TYPE = '세단'
ORDER BY C.CAR_ID DESC;