SELECT F1.ID, F2.FISH_NAME, F1.LENGTH
FROM FISH_INFO F1 JOIN FISH_NAME_INFO F2
ON F1.FISH_TYPE = F2.FISH_TYPE
WHERE F1.LENGTH = (
    SELECT MAX(F3.LENGTH)
    FROM FISH_INFO F3
    WHERE F1.FISH_TYPE = F3.FISH_TYPE
    GROUP BY(FISH_TYPE)
)