SELECT SUM(SCORE) SCORE, E.EMP_NO, EMP_NAME, POSITION, EMAIL
FROM HR_EMPLOYEES E JOIN HR_GRADE G
ON E.EMP_NO = G.EMP_NO
GROUP BY E.EMP_NO
HAVING SUM(SCORE) = (SELECT MAX(R.RESULT)
                     FROM (SELECT SUM(SCORE) RESULT, EMP_NO
                           FROM HR_GRADE
                           GROUP BY EMP_NO) AS R)
