SELECT P.CATEGORY, S.MAX_PRICE, P.PRODUCT_NAME
FROM FOOD_PRODUCT P
JOIN (SELECT MAX(PRICE) MAX_PRICE, CATEGORY
    FROM FOOD_PRODUCT
    WHERE CATEGORY IN ('과자', '국', '김치', '식용유')
    GROUP BY CATEGORY) S
ON P.CATEGORY = S.CATEGORY
AND P.PRICE = S.MAX_PRICE
ORDER BY 2 DESC