WITH AVG_FISH AS (
    SELECT FISH_TYPE, AVG(CASE WHEN LENGTH IS NULL THEN 10 ELSE LENGTH END) AS AVG_LENGTH
    FROM FISH_INFO
    GROUP BY FISH_TYPE
)
SELECT COUNT(*) AS FISH_COUNT, MAX(LENGTH) AS MAX_LENGTH, FISH_TYPE
FROM FISH_INFO
WHERE FISH_TYPE IN (SELECT FISH_TYPE FROM AVG_FISH WHERE AVG_LENGTH >= 33)
GROUP BY FISH_TYPE
ORDER BY FISH_TYPE;
